# Generated by Django 6.0.3 on 2026-04-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_searchrequest_max_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchrequest',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='searchrequest',
            name='max_mileage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchrequest',
            name='ordering',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
