# Generated by Django 6.0.3 on 2026-09-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_searchrequest_brand_searchrequest_max_mileage_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['price'], name='car_price_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['year'], name='car_year_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['mileage'], name='car_mileage_idx'),
        ),
        migrations.AddIndex(
            model_name='searchrequest',
            index=models.Index(fields=['-created_at'], name='search_created_idx'),
        ),
    ]
